### ISSUE TITLE
Добавить возможность использовать X-Cloud-Org-ID вместо X-Org-ID

### ISSUE THREAD

**Issue by sinitsynme** [evrone-erp/yandex-tracker-action#11]
Привет!

Пытался подключить action к своему проекту, добавил все secret-ы как положено, но action не находил задачи. 
Проанализировал код скрипта и обнаружил, что сейчас в нем нет поддержки X-Cloud-Org-ID. 

В API Tracker в запросах имеются два вида заголовков с ID организации:

* X-Org-ID или X-Cloud-Org-ID
```
Идентификатор организации. Узнать его можно на [странице организаций Tracker](https://tracker.yandex.ru/admin/orgs)
.

Если к Tracker привязана только организация Яндекс 360 для бизнеса, используется заголовок X-Org-ID.
Если к Tracker привязана только организация Yandex Cloud Organization, используется заголовок X-Cloud-Org-ID.
Если к Tracker одновременно привязаны организации Яндекс 360 для бизнеса и Yandex Cloud Organization, используется заголовок X-Org-ID и идентификатор организации Яндекс 360 для бизнеса.
```

У меня ситуация №2 (есть только X-Cloud-Org-ID). А чтобы получить X-Org-ID, нужно регистрировать компанию в 360 (а платить за это неохота). 

Было бы неплохо, если бы action мог работать с различными вариантами заголовков

**Comment by soltanoff** [comment]
Приветсвую! 

Спасибо за обратную связь, поддержку `X-Cloud-Org-ID` добавим.

**Comment by soltanoff** [comment]
Обновил список инпутов: 

- `token`: **Обязательно** Токен Github.
- `yandex_oauth2_token`: **Обязательно** Токен Yandex oauth2. Вам необходимо зарегистрировать приложение OAUTH2, а затем
  получить токен пользователя. [Документация](https://yandex.ru/dev/id/doc/dg/oauth/concepts/about.html).
- `yandex_org_id`: **Обязательно** Идентификатор организации, зарегистрированной в Yandex Tracker.
- `is_yandex_cloud_org`: **Опционально** Если к Трекеру применяется только организация Yandex Cloud Organization,
  используется заголовок `X-Cloud-Org-ID`.
- `ignore`: **Опционально** Игнорируемые задачи, разделенные запятыми.
- `tasks`: **Опционально** Ключ задачи, которую нужно переместить на доску.
- `task_url`: **Опционально** Значение по умолчанию - `false`. Установите в `true`, если вы хотите прокомментировать PR
  с URL задачи.
- `to`: **Опционально** Укажите, куда вы хотите переместить задачу. По умолчанию - `in_review` **для открытых PR
  и `resolve` для закрытых PR**.


Чтобы использовать `yandex_org_id` как идентификатор Yandex Cloud Organization, нужно выставить `is_yandex_cloud_org` как `true`.

**Comment by soltanoff** [comment]
New Release tag: [v1.2.0](https://github.com/evrone-erp/yandex-tracker-action/releases/tag/v1.2.0)

**Comment by sinitsynme** [comment]
Спасибо!)
